apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # strategy:
  #   type: "RollingUpdate"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # 1.14.2 to 1.22.1
        image: nginx:1.22.1
        ports:
        - containerPort: 80